language: php
php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - composer install
  - composer dump-autoload -o
  - sudo cp php/config-default.php php/config.php
script:
# ALL THE BUILD COMMANDS HERE
phpunit --coverage-text
