language: php
php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - composer install
#  - composer dump-autoload -o
  - sudo cp php/config-test.php php/config.php
  - sudo mv php/tests/bootstrap.php php/tests/bootstrap_
script: phpunit --coverage-text
